getgenv().Games = {
    [116495829188952] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/Noti.Lua", -- Dead Rails
    [2753915549] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/BloxFruits.Lua", -- Blox Fruit Sea 1
    [4442272183] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/BloxFruits.Lua", -- Blox Fruit Sea 2
    [7449423635] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/BloxFruits.Lua", -- Blox Fruit Sea 3
    [16732694052] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/Fisch.Lua", -- Fisch
    [16480898254] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/EatTheWorld.Lua", -- EatTheWorld
    [18668065416] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/BlueLock.Lua", -- Blue Lock
    [70876832253163] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/DeadRails.Lua", -- Dead Rails
    [116614712661486] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/AntiAfk.Lua", -- Dead Rails Afk
    [87039211657390] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/AriseCrossover.Lua", -- AriseCrossover
    [128336380114944] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/AriseCrossover.Lua", -- AriseCrossover
    [72829404259339] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/AnimeRangersX.Lua", -- AnimeRangersX
}
