getgenv().Games = {
    [2753915549] = "https://raw.githubusercontent.com/HieuNeMn/Game-List/refs/heads/main/Blox%20Fruits.Lua", -- Blox Fruit Sea 1
    [4442272183] = "https://raw.githubusercontent.com/HieuNeMn/Game-List/refs/heads/main/Blox%20Fruits.Lua", -- Blox Fruit Sea 2
    [7449423635] = "https://raw.githubusercontent.com/HieuNeMn/Game-List/refs/heads/main/Blox%20Fruits.Lua", -- Blox Fruit Sea 3
    [16732694052] = "https://raw.githubusercontent.com/HieuNeMn/Game-List/refs/heads/main/Fisch.Lua", -- Fisch
    [116605585218149] = "https://raw.githubusercontent.com/HieuNeMn/Game-List/refs/heads/main/GoFishing.Lua", -- Go Fishing
}
