getgenv().Games = {
    [2753915549] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/BloxFruits.Lua", -- Blox Fruit Sea 1
    [4442272183] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/BloxFruits.Lua", -- Blox Fruit Sea 2
    [7449423635] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/BloxFruits.Lua", -- Blox Fruit Sea 3
    [16732694052] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/Fisch.Lua", -- Fisch
    [16480898254] = "https://raw.githubusercontent.com/HitasTrick/Script/refs/heads/main/EatTheWorld.Lua", -- EatTheWorld
}
